language: python

python:
    - 3.7

sudo: required

branches:
    - master
    - develop
    - /^v.*$/

# Builds Test

env: 
    matrix:
      - PLATFORMIO_CI_SRC=examples/For_H_bridge
      - PLATFORMIO_CI_SRC=examples/For_half_bridge
      - PLATFORMIO_CI_SRC=examples/BLDC_HALL

install: 
  - pip install -U platformio
  - platformio platform install -f infineonxmc
  - platformio platform install -f atmelavr

script: 
  - platformio ci --lib="." --board=uno --board=xmc1100_boot_kit --board=xmc4700_relax_kit 
